config/routes.rb
PostOnWall::Application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  match '/auth/facebook/update_token' => 'omniauth_callbacks#update_token', as: :update_token

  resources :users, only: [:index, :new]
  post 'create_user' => 'users#create'
  get 'profile' => 'users#show'
  delete 'revoke_publish_permission' => 'users#revoke_publish_permission'
  put 'post_on_wall' => 'users#post_on_wall'

  root to: 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)
#  admin                  :boolean
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  provider               :string(255)
#  uid                    :string(255)
#  token                  :string(255)
#  publish_permission     :boolean
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :remember_me, :provider, :uid


  scope :normal_users, ->{ where(admin: [nil, false])}

  def self.find_for_facebook_oauth(auth)
    find_or_initialize_by_email(auth.info.email).tap do |user|
      user.password = Devise.friendly_token[0,20] if user.new_record?
      user.provider = auth.provider
      user.uid = auth.uid
      user.token = auth.credentials.token
      user.publish_permission =  FbGraph::User.me(user.token).permissions.include?(:publish_stream)
      user.save
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end


  def revoke_publish_permission
    FbGraph::User.me(token).revoke! :publish_stream
    self.update_attribute :publish_permission, false
  end

  def post_on_wall(text = nil)
    text ||= 'This is test message'
    FbGraph::User.me(token).feed!( message: text)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :authenticate_user!

  protected
    def after_sign_in_path_for(resource)
      redirect_path_according_to_role
    end

    def redirect_path_according_to_role
      if current_user.admin?
        users_path
      else
        profile_path
      end
    end

    def redirect_according_to_role
      redirect_to redirect_path_according_to_role
    end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.find_for_facebook_oauth(request.env["omniauth.auth"] )

    # debugger
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format? and @user.publish_permission?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authenticate_user!, only: [:home]
  before_filter :verify_and_redirect_authenticate_user

  private
    def verify_and_redirect_authenticate_user
      redirect_according_to_role if current_user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :validation_admin, only: [:index, :new, :create]

  # GET /users
  def index
    @users = User.normal_users

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /users/1
  def show
    @user = current_user

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /users/new
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # POST /users
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to [:users], notice: 'User was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def revoke_publish_permission
    current_user.revoke_publish_permission
    redirect_to :back
  end

  def post_on_wall
    current_user.post_on_wall
    redirect_to :back, notice: 'Posted successfully on your wall.'
  end

  protected
    def validation_admin
      redirect_to redirect_path_according_to_role, notice: 'Unauthorized access' unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <a href="/" class="navbar-brand">My Awesome app</a>
        </div>
        <div class="navbar-collapse collapse" id="navbar-main">
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
            <li><%= link_to current_user.try( :email), 'javascript:void(0)' %></li>
              <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
            <% else %>
              <li>
                <%= link_to('Login', new_user_session_path)  %>
              </li>
              <li>
                <%= link_to('Sign Up', new_user_registration_path)  %>
              </li>
              <li>
                <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostOnWall</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <div class="row top-padded">

       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/pages/home.html.erb
<div class="page-header" id="banner">
  <div class="row">
    <div class="col-lg-6">
      <h1>Yeah, you got it right</h1>
      <p class="lead">Just login and share on Facebook</p>
    </div>
    <div class="col-lg-6" style="padding: 15px 15px 0 15px;">
      <div class="well sponsor">
        <%= link_to 'http://bootswatch.com', target: '_blank' do -%>
          <h4 style="margin-bottom: 0.4em;">Free themes for Bootstrap</h4>
          <div class="clearfix">
            <p>Easy to install</p>
            <p>Open source</p>
            <p>Lots of free popular templates and themes</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  </div>

app/views/users/_form.html.erb
<%= form_for @user, url: create_user_path, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%#= user.admin %></td>
        <td><%#=l user.created_at %></td>
        <td>
          <%#= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-mini' %>
          <%#= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Create User', new_user_path, class: 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <% if current_user.publish_permission? %>
    <%= link_to "Link to Facebook", 'javascript:void(0)' , class: 'btn btn-primary btn-lg disabled' %>
    <%= link_to "Unlink to Facebook", revoke_publish_permission_path , class: 'btn btn-primary btn-lg', confirm: 'Are you sure', method: :delete %>
    <%= link_to "Post to facebook", post_on_wall_path , class: 'btn btn-primary btn-lg', method: :put %>
  <% else %>
    <%= link_to "Link to Facebook", user_omniauth_authorize_path(:facebook, scope: 'email,publish_actions') , class: 'btn btn-primary btn-lg' %>
    <%= link_to "Unlink to Facebook", "javascript:void(0)" , class: 'btn btn-primary btn-lg disabled' %>
    <%= link_to "Post to facebook", "javascript:void(0)" , class: 'btn btn-primary btn-lg disabled' %>
  <% end %>
</div>